language: python
os: linux
dist: bionic
cache:
  - pip
  - cargo

stages:
  - test
  - deploy
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2020-02-03
  - RUST_BACKTRACE=1

python_test: &python_test
  stage: test
  before_install:
    - source ci/travis/setup_rust.sh
    - cd nblast-py
    - pip install -r requirements.txt
  install:
    - maturin develop
  script:
    - pytest -v

jobs:
  include:

    # TEST

    - stage: test
      name: "test rust"
      before_install:
        - source ci/travis/setup_rust.sh
      install:
        - cd nblast-rs
        - cargo build
      script:
        - cargo test
        - cargo clippy
        - cargo fmt -- --check

    - stage: test
      name: "lint python"
      python: 3.8
      before_install:
        - cd nblast-py
        - pip install $(grep '^black' requirements.txt)
        - pip install $(grep '^flake8' requirements.txt)
      install: true  # override default
      script:
        - flake8 pynblast tests
        - black --check pynblast tests

    - <<: *python_test
      name: "test py36"
      python: 3.6

    - <<: *python_test
      name: "test py37"
      python: 3.7

    - <<: *python_test
      name: "test py38"
      python: 3.8

    # DEPLOY

    - stage: deploy
      name: "PyPI (linux)"
      if: tag =~ /^py-v\d+.*/
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6
            - python3.7
            - python3.8
      before_install:
        - source ci/travis/setup_rust.sh
      install:
        - cd nblast-py
        - pip install $(grep '^maturin' requirements.txt)
      script:
        - maturin publish -u $PYPI_USERNAME -p $PYPI_PASSWORD -i python3.8 -i python3.7 -i python3.6

    - stage: deploy  # implied
      name: "crates.io"
      if: tag =~ /^rs-v\d+.*/
      before_install:
        - source ci/travis/setup_rust.sh
      script:
        - cd nblast-rs
        - cargo publish --token $CARGO_TOKEN
