language: python
os: linux
dist: xenial

stages:
  - test
  - deploy
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2020-02-03
  - RUST_BACKTRACE=1
  - PYPI_USERNAME=clbarnes

rust_test: &rust_test
  stage: test
  before_install:
    - source ci/travis/setup_rust.sh
  script:
    - cargo test --verbose

python_test: &python_test
  stage: test
  before_install:
    - source ci/travis/setup_rust.sh
    - cd nblast-py
    - pip install -r requirements.txt
  install:
    - maturin develop
  script:
    #- cargo test --verbose  # "linking with cc failed"?
    - pytest -v
    - flake8 pynblast tests
    - black --check pynblast tests

bash_deploy: &bash_deploy
  stage: deploy
  if: tag =~ /^py-v\d+.*/
  before_install:
    - source ci/travis/setup_rust.sh
  install:
    - cd nblast-py
    - pip install $(grep '^maturin' requirements.txt)
  script:
    - maturin publish -u $PYPI_USERNAME -p $PYPI_PASSWORD -i python3.8 -i python3.7 -i python3.6

jobs:
  include:
    - <<: *rust_test
      name: "test rust"
    - <<: *python_test
      name: "test py36"
      python: 3.6
    - <<: *python_test
      name: "test py37"
      python: 3.7
    - <<: *python_test
      name: "test py38"
      python: 3.8
    - <<: *bash_deploy
      name: "Linux PyPI"
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6
            - python3.7
            - python3.8
    - <<: *bash_deploy
      os: osx
      name: "OSX PyPI"
      addons:
        homebrew:
          packages:
            - python3.6
            - python3.7
            - python3.8
    - # stage: deploy  # deploy stage is implied
      name: "deploy to crates.io"
      if: tag =~ /^rs-v\d+.*/
      before_install:
        - source ci/travis/setup_rust.sh
      script:
        - cd nblast-rs
        - cargo publish --token $CARGO_TOKEN
